version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud_docs
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=mysql+pymysql://flaskuser:flaskpass@mysql/cloud_docs
      - SECRET_KEY=dev-key
      - FLASK_APP=app.py
      - PYTHONPATH=/app/backend
    command: >
      sh -c "python init_db.py &&
            flask run --host=0.0.0.0 --port=5001"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql_data:
