name: CD to GHCR

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/doc-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert image repo to lowercase
        id: lower_repo
        run: |
          echo "tag=$(echo $IMAGE_REPO | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push backend image
        run: |
          docker build -f backend/Dockerfile -t ghcr.io/${{ github.repository_owner }}/doc-backend:latest .
          docker push ghcr.io/${{ github.repository_owner }}/doc-backend:latest
